# Site settings
author: Chad L
title: Lessons learned Coding
header-img: img/home-bg.png
email: chadlengefeld@gmail.com
copyright_name: Chad L
description: > # this means to ignore newlines until "baseurl:"
  Following a full-stack developer's journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  LostnAustin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
